# PostgreSQL and Azure Blob Storage credentials for Materialize
# This template uses environment variable substitution for security
# 
# Required environment variables (set via: source .env):
# - POSTGRES_HOST: PostgreSQL server hostname
# - POSTGRES_USERNAME: PostgreSQL username  
# - POSTGRES_PASSWORD: PostgreSQL password
# - AZURE_STORAGE_ACCOUNT: Azure storage account name
# - AZURE_STORAGE_CONTAINER: Azure blob container name
# - AZURE_STORAGE_SAS_TOKEN: Azure blob storage SAS token
#
# Deploy with: source .env && envsubst < postgres-secret.yaml | kubectl apply -f -

apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: materialize-system
type: Opaque
stringData:
  # Keys expected by Materialize
  metadata_backend_url: "postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/materialize?sslmode=require"
  persist_backend_url: "https://${AZURE_STORAGE_ACCOUNT}.blob.core.windows.net/${AZURE_STORAGE_CONTAINER}?${AZURE_STORAGE_SAS_TOKEN}"
  
  # Additional connection details
  connection-string: "postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/materialize?sslmode=require"
  host: "${POSTGRES_HOST}"
  port: "5432"
  database: "materialize"
  username: "${POSTGRES_USERNAME}"
  password: "${POSTGRES_PASSWORD}"