apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: materialize-system
type: Opaque
stringData:
  connection-string: "postgresql://mzadmin:MaterializeDB123!@mz-postgres-1754509666.postgres.database.azure.com/materialize?sslmode=require"
  host: "mz-postgres-1754509666.postgres.database.azure.com"
  port: "5432"
  database: "materialize"
  username: "mzadmin"
  password: "MaterializeDB123!"