# External Secrets Operator configuration for Azure Key Vault integration
# This allows Flux to automatically deploy secrets from Azure Key Vault
#
# Prerequisites:
# 1. Install External Secrets Operator: kubectl apply -k "github.com/external-secrets/external-secrets/config/crds?ref=main"
# 2. Create Azure Key Vault with secrets
# 3. Configure Azure service principal or managed identity

apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: materialize-keyvault
  namespace: materialize-system
spec:
  provider:
    azurekv:
      # Your Azure Key Vault URL
      vaultUrl: "https://your-keyvault.vault.azure.net/"
      authType: ManagedIdentity
      # Alternative: Service Principal
      # authType: ServicePrincipal
      # authSecretRef:
      #   clientId:
      #     name: azure-secret
      #     key: client-id
      #   clientSecret:
      #     name: azure-secret
      #     key: client-secret
      #   tenantId:
      #     name: azure-secret
      #     key: tenant-id
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-credentials
  namespace: materialize-system
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: materialize-keyvault
    kind: SecretStore
  target:
    name: postgres-credentials
    creationPolicy: Owner
  data:
  - secretKey: metadata_backend_url
    remoteRef:
      key: postgres-metadata-url
  - secretKey: persist_backend_url
    remoteRef:
      key: azure-blob-persist-url
  - secretKey: host
    remoteRef:
      key: postgres-host
  - secretKey: username
    remoteRef:
      key: postgres-username
  - secretKey: password
    remoteRef:
      key: postgres-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: materialize-users
  namespace: materialize-system
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: materialize-keyvault
    kind: SecretStore
  target:
    name: materialize-users
    creationPolicy: Owner
  data:
  - secretKey: admin-password
    remoteRef:
      key: materialize-admin-password