apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: materialize-azure-gitops
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  url: https://github.com/MaterializeIncLabs/materialize-azure-gitops